### ISSUE TITLE
licenses misspelling for metadata

### ISSUE THREAD

**Issue by kalekaneki** [Qbox-project/qbx_cityhall#13]
### Summary

basically licenses is spelled as licences for our metadata attribute that we persist to the db

### Issue at hand

![image](https://github.com/Qbox-project/qbx-cityhall/assets/46171436/bd2977b4-350c-429a-8c30-978d326499cc)

### Additional context

My question is it okay for us to change because we are still WIP stage? I could see this messing up some servers running qbox right now.

### Last Updated

today

### Custom Resources

no

### Resource Rename

no

**Comment by Manason** [comment]
That's the british spelling https://proofed.com/writing-tips/word-choice-license-vs-licence/
