### ISSUE TITLE
Licenses not displaying

### ISSUE THREAD

**Issue by BerkieBb** [Qbox-project/qbx_cityhall#14]
### Summary

The licenses to buy don't display

### Reproduction

1. Open cityhall menu
2. Navigate to licenses
3. Be met with an empty menu

### Expected behavior

![image](https://github.com/Qbox-project/qbx-cityhall/assets/82737367/cbd851b6-f864-40b1-bb22-1285bab83b31)

### Actual behavior

![image](https://github.com/Qbox-project/qbx-cityhall/assets/82737367/5e3eda33-6185-4c8b-9129-857b20024740)

### Last Updated

today

### Custom Resources

no

### Resource Rename

no

**Comment by mockdot** [comment]
Fixed on #15
